### ISSUE TITLE
Can't find card

### ISSUE THREAD

**Issue by SanderH030** [custom-cards/stack-in-card#62]
Hi,

I try to use a (custom) stack-in-card. I installed it via HACS:

<img width="1183" alt="image" src="https://github.com/thomasloven/hass-config/assets/121697071/6be0bb7f-a445-4724-ac20-12894ce788d5">

When I try to add this card to my dashboard I can't find the card? Everything is installed correctly. I checked my www folder:

<img width="980" alt="image" src="https://github.com/thomasloven/hass-config/assets/121697071/de7cbdab-e95b-4cc3-bc86-796b4a826214">

<img width="269" alt="image" src="https://github.com/thomasloven/hass-config/assets/121697071/6bb2e62f-d92e-4071-99c2-6dfb6aa054d4">

Does any of you guys know what's going wrong?

**Comment by ildar170975** [comment]
Nothing is wrong.
Custom cards are not obliged to be in "Add a card" dialog, I do not have it too:
![изображение](https://github.com/custom-cards/stack-in-card/assets/71872483/5fb06861-21c1-4009-90bf-33451da4e936)
Many custom cards are defined by yaml only, not by UI.
Select "Manual" and type whatever you need.
I myself usually select ANY card, then switch to "yaml" and type my code.

**Comment by SanderH030** [comment]
> Nothing is wrong.
> Custom cards are not obliged to be in "Add a card" dialog, I do not have it too:
> ![изображение](https://user-images.githubusercontent.com/71872483/268758646-5fb06861-21c1-4009-90bf-33451da4e936.png)
> Many custom cards are defined by yaml only, not by UI.
> Select "Manual" and type whatever you need.
> I myself usually select ANY card, then switch to "yaml" and type my code.

Ah, perfect! Thank you :)
