### ISSUE TITLE
Dropdown values not visible in iOS Home Assistant client

### ISSUE THREAD

**Issue by peyn** [custom-cards/stack-in-card#68]
**Checklist:**
- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Home Assistant Application for iOS

**Description of problem:**
When using the "Stack in Card" card for Home Assistant dashboard some values of dropdown lists are not visible in the iOS client.
It works fine in a PC browser, i.e. the dropdown in the card is being adjusted to fit all values.

PC:
![image](https://github.com/custom-cards/stack-in-card/assets/8287189/a80169ba-3c0f-4676-bee9-a86c38412d37)

The card is shifted top to show all 3 dropdown values:
![image](https://github.com/custom-cards/stack-in-card/assets/8287189/17db53e2-8964-4605-a131-c9af484d48a2)

iOS:
All 3 options visible at the top most input:
![image](https://github.com/custom-cards/stack-in-card/assets/8287189/35e5d667-6ade-49ae-b333-4dac1610f904)

Some options not available:
![image](https://github.com/custom-cards/stack-in-card/assets/8287189/00e20348-6700-4f6a-a238-8cc7c9a58aec)
![image](https://github.com/custom-cards/stack-in-card/assets/8287189/88a4eb9f-79f8-4f49-944a-ffb29ae6a911)

Kind regards,
Mateusz

**Comment by ildar170975** [comment]
Same as https://github.com/custom-cards/stack-in-card/issues/40

**Comment by peyn** [comment]
Yes, thank you, the solution provided there solves the issue.

Kind regards,
Mateusz
